const products = [
    {
      image: "./images/Products/1.png",
      name: "Tokyo Sour",
      type: "Ale",
      subtype: "Gose",
      alchohol: 4.3,
      price: 50,
    },
    {
      image: "./images/Products/2.png",
      name: "Centennial IPA",
      type: "Ale",
      subtype: "IPA",
      alchohol: 0,
      price: 35,
    },
    {
      image: "./images/Products/3.png",
      name: "RIBA",
      type: "Lager",
      subtype: "Unfiltered Pils",
      alchohol: 4.5,
      price: 25,
    },
    {
      image: "./images/Products/4.png",
      name: "Lust For Life",
      type: "Ale",
      subtype: "DDH IPA",
      alchohol: 0,
      price: 35,
    },
    {
      image: "./images/Products/5.png",
      name: "7 Hop 7 Grain",
      type: "Ale",
      subtype: "DDH IPA",
      alchohol: 0,
      price: 35,
    },
    {
        image: "./images/Products/6.png",
        name: "Liquid Cocaine",
        type: "Ale",
        subtype: "Double IPA",
        alchohol: 9,
        price: 75,
    },
    {
        image: "./images/Products/7.png",
        name: "IDAHO 7",
        type: "Ale",
        subtype: "IPA",
        alchohol: 0,
        price: 35,
    },
  ];